/**
 * Daily excerpt-of-the-day generation.
 *
 * Picks a random previously-finished bookmark and uses an LLM to extract one
 * memorable quote. Result is cached per user per day.
 *
 * Tz caveat: V1 buckets days by UTC. Per-user timezones are V2.
 *
 * Soft enhancement — errors are logged and swallowed; never throws.
 *
 * Output discipline: uses generateObject + Zod so the model can NEVER bleed
 * the prompt instructions into the output (an earlier free-tier chat model
 * was returning meta-commentary like "We need to extract ONE punchy quote…").
 */

import { generateObject } from "ai";
import { and, eq, sql } from "drizzle-orm";
import { z } from "zod";

import { db } from "@/db";
import { bookmarks, dailyExcerpts } from "@/db/schema";
import { getModel } from "@/lib/ai";

const MAX_SOURCE_CHARS = 6000;
const MAX_EXCERPT_CHARS = 320;
const MIN_EXCERPT_CHARS = 12;

const QuoteSchema = z.object({
  quote: z
    .string()
    .min(MIN_EXCERPT_CHARS)
    .max(MAX_EXCERPT_CHARS)
    .describe(
      "A single punchy, memorable sentence or short passage copied verbatim from the article body. Plain text only. No surrounding quotation marks. No commentary.",
    ),
});

export type DailyExcerptResult = {
  excerpt: string;
  bookmarkId: string;
  bookmarkTitle: string;
  bookmarkDomain: string | null;
};

function sanitizeExcerpt(raw: string): string {
  let text = raw.trim().replace(/\s+/g, " ");
  text = text.replace(/^["“”'‘’`]+|["“”'‘’`]+$/g, "").trim();
  if (text.length > MAX_EXCERPT_CHARS) {
    text = text.slice(0, MAX_EXCERPT_CHARS).trimEnd();
  }
  return text;
}

/**
 * Reject obvious prompt-leakage / meta-commentary so we never display
 * "We need to extract a quote…" instead of an actual quote.
 */
function looksLikeMetaCommentary(text: string): boolean {
  const t = text.toLowerCase();
  const redFlags = [
    "we need to",
    "i need to",
    "extract one",
    "extract a quote",
    "the article is",
    "punchy",
    "memorable quote",
    "no quotation marks",
    "no commentary",
    "1-3 sentences",
    "max 280 characters",
    "max 320 characters",
    "return only",
    "as written",
  ];
  return redFlags.some((flag) => t.includes(flag));
}

function todayUtcDateString(): string {
  return new Date().toISOString().slice(0, 10);
}

export async function getOrCreateDailyExcerpt(
  userId: string,
): Promise<DailyExcerptResult | null> {
  try {
    const today = todayUtcDateString();

    const [existing] = await db
      .select({
        excerpt: dailyExcerpts.excerpt,
        bookmarkId: dailyExcerpts.bookmarkId,
        bookmarkTitle: bookmarks.title,
        bookmarkDomain: bookmarks.domain,
      })
      .from(dailyExcerpts)
      .innerJoin(bookmarks, eq(dailyExcerpts.bookmarkId, bookmarks.id))
      .where(
        and(eq(dailyExcerpts.userId, userId), eq(dailyExcerpts.date, today)),
      )
      .limit(1);

    if (existing) {
      // Self-heal: if a cached excerpt was generated by an older prompt that
      // leaked instructions (we shipped a fix), discard it and regenerate.
      if (
        existing.excerpt.length >= MIN_EXCERPT_CHARS &&
        !looksLikeMetaCommentary(existing.excerpt)
      ) {
        return {
          excerpt: existing.excerpt,
          bookmarkId: existing.bookmarkId,
          bookmarkTitle: existing.bookmarkTitle ?? "Untitled",
          bookmarkDomain: existing.bookmarkDomain,
        };
      }
      console.warn(
        "[excerpt] discarding stale meta-commentary excerpt for",
        existing.bookmarkId,
      );
      await db
        .delete(dailyExcerpts)
        .where(
          and(eq(dailyExcerpts.userId, userId), eq(dailyExcerpts.date, today)),
        );
    }

    const [candidate] = await db
      .select({
        id: bookmarks.id,
        title: bookmarks.title,
        domain: bookmarks.domain,
        content: bookmarks.content,
        summary: bookmarks.summary,
      })
      .from(bookmarks)
      .where(
        and(
          eq(bookmarks.userId, userId),
          eq(bookmarks.isRead, true),
          sql`(${bookmarks.content} IS NOT NULL OR ${bookmarks.summary} IS NOT NULL)`,
        ),
      )
      .orderBy(sql`random()`)
      .limit(1);

    if (!candidate) return null;

    const sourceText = candidate.content
      ? candidate.content.slice(0, MAX_SOURCE_CHARS)
      : (candidate.summary ?? "");

    if (!sourceText.trim()) return null;

    const title = candidate.title ?? "Untitled";

    const system = `You select a single short verbatim quote from a provided article. Output strict JSON matching the schema. The "quote" field MUST be copied word-for-word from the article body, must be 1-3 sentences, must not include surrounding quotation marks, and must not contain any commentary or instructions.`;

    const user = `Article title: ${title}\n\nArticle body:\n${sourceText}`;

    const { object } = await generateObject({
      model: getModel(),
      schema: QuoteSchema,
      system,
      prompt: user,
      temperature: 0.2,
    });

    const excerpt = sanitizeExcerpt(object.quote);
    if (!excerpt || excerpt.length < MIN_EXCERPT_CHARS) {
      console.warn(`[excerpt] empty/too-short excerpt for user ${userId}`);
      return null;
    }
    if (looksLikeMetaCommentary(excerpt)) {
      console.warn(
        `[excerpt] rejected meta-commentary output for user ${userId}: ${excerpt.slice(0, 80)}…`,
      );
      return null;
    }

    await db
      .insert(dailyExcerpts)
      .values({
        userId,
        date: today,
        bookmarkId: candidate.id,
        excerpt,
      })
      .onConflictDoNothing({
        target: [dailyExcerpts.userId, dailyExcerpts.date],
      });

    // Re-read after insert (handles ON CONFLICT race where another request won).
    const [final] = await db
      .select({
        excerpt: dailyExcerpts.excerpt,
        bookmarkId: dailyExcerpts.bookmarkId,
        bookmarkTitle: bookmarks.title,
        bookmarkDomain: bookmarks.domain,
      })
      .from(dailyExcerpts)
      .innerJoin(bookmarks, eq(dailyExcerpts.bookmarkId, bookmarks.id))
      .where(
        and(eq(dailyExcerpts.userId, userId), eq(dailyExcerpts.date, today)),
      )
      .limit(1);

    if (!final) return null;

    return {
      excerpt: final.excerpt,
      bookmarkId: final.bookmarkId,
      bookmarkTitle: final.bookmarkTitle ?? "Untitled",
      bookmarkDomain: final.bookmarkDomain,
    };
  } catch (err) {
    console.error(
      `[excerpt] getOrCreateDailyExcerpt failed for ${userId}:`,
      err instanceof Error ? err.message : err,
    );
    return null;
  }
}
